### ISSUE TITLE
The extension is causing git warning's in the output panel

### ISSUE THREAD

**Issue by amandatennent** [DataDog/datadog-for-vscode#12]
When the datadog extension is enabled, I'm getting a constant stream of warnings:

```[warning] Failed to get repository realpath for: "vscode.git.Git". Error: ENOENT: no such file or directory, realpath 'vscode.git.Git'```

I have disabled all extensions, and it only happens when the datadog extension is enabled. It seems to only be happening with version 1.5.0 and later.

**Comment by jfree** [comment]
Thanks for the report, we're on it.

**Comment by robertohuertasm** [comment]
Hi @amandatennent, we would need a little bit more information about your setup in order to reproduce this.  It would be nice if you could tell us about:
- Your OS
- Specific VS Code version
- Does this happen in all your repositories?
- Are you in a remote scenario? (e.g. WSL, Dev Container, CodeSpaces, vscode.dev...)

For all the git operations, we're leveraging VS Code git support. According to the error your getting, there's a good chance that you have git support disabled.

Please, take a look into your settings and look for `git enable`. Let us know if you have it disabled. If that's the case, enable that flag and let us know if the problem persists.

<img width="600" alt="image" src="https://github.com/DataDog/datadog-for-vscode/assets/696981/706af7c6-31a4-4d8f-a738-4f1a0439318d">

**Comment by robertohuertasm** [comment]
@amandatennent, we identified the issue and were able to reproduce. This will get fixed in the next release. Thank you very much for your feedback! 🙌🏻

**Comment by brentshulman-silkline** [comment]
Has the fix been released? I just found this issue after much searching .....

**Comment by jfree** [comment]
Not yet, but we expect to make a new release quite soon.

**Comment by jfree** [comment]
The latest release (v1.11.0) includes the fix.  Thanks for bearing with us.

https://marketplace.visualstudio.com/items?itemName=Datadog.datadog-vscode
